### ISSUE TITLE
Konfiguracja loggera

### ISSUE THREAD

**Issue by kr5ture** [qverkk/university-scheduler#20]
## Intro

Niezwykle istotne jest, aby w aplikacji zadbać o odpowiedni poziom logowania. Przeglądając wpisy powinniśmy zawsze być w stanie stwierdzić co dzieje się w aplikacji. W przypadku GUI - kliknięcia wywołują odpowiednie akcje, a w przypadku serwera - żądania HTTP są obsługiwane. W systemach produkcyjnych nieustannie zachodzi powtarzająca się potrzeba sprawdzenia czy jakaś akcja miała miejsce i jaki był jej rezultat. Pomijając temat logowania we wczesnej fazie developmentu, skazujemy się na późniejszy brak możliwości weryfikacji działania aplikacji (działa sobie jakiś .exe, ale nie jesteśmy w stanie powiedzieć, czy czasem aplikacja nie zawisła na jakiejś nieskończonej pętli - albo nie będziemy w stanie stwierdzić, dlaczego dany przycisk nie działa - czy w aplikacji jest coś nie tak, czy serwer backendowy nie odpowiada?).

### Możliwości

Loggery są wysoce konfigurowalne:
* `logger` - definiuje, które logi (o jakim poziomie - o tym niżej) dla danego pakietu/klasy zostaną przekazane do `appender`'a
* `appender` - agregator logów przekazanych przez `logger`. Definiuje, gdzie logi mają być zapisane np. wypiswane na `stdout` oraz zapisywane do jakiegoś pliku (w niektórych firmach logi są wysyłane po `UDP` do serwera zbierającego)

### Poziom logowania

Podczas pisania kodu podejmujemy decyzję jakie informacje chcemy mieć w logach i jak dokładne (zapisywanie parametrów) one będą. Poziom logowania określa krytyczność wpisów - im wyższy poziom, tym wpis jest ważniejszy. "Ważność" wpisu wyraża się poziomem, na którym został zalogowany. W zależności od użytej biblioteki, można się spotkać z większą (bardziej dokładne - granulacja) lub mniejszą liczbą poziomów, jednak generalnie wszędzie można spotkać:

* `ERROR` - Najwyższy poziom. Na tym poziomie powinny zostać zapisywane wszelkie sytuacje problematyczne, wymagające natychmiastowej reakcji.
* `WARN` - Niespodziewane błędy, czy to aplikacyjne (np. niektóre wyjątki), czy biznesowe.
* `INFO` - Informacyjne wpisy, które czytającemu loga zapewnią, że w systemie dzieją się konkretne operacje (np. fakt nadejścia żądania HTTP do serwera lub wywołanie konkretnych akcji, zdarzeń w aplikacji).
* `DEBUG` - Wszystkie logi, które nie pasują do poziomu `INFO`, a są w stanie pomóc w dokładniejszym śledzeniu działania aplikacji.
* `TRACE` - Przeznaczony do najbardziej szczegółowego logowania, np. wpisy przed i po każdej wywołanej metodzie + pełne reprezentacje obiektów parametrów wejściowych/zwracanych.

Poziomy są ułożone w hierarchi, tzn. `logger` z ustawionym poziomiem `DEBUG`, będzie przekazywał wszystkie wpisy o tym poziomie oraz poziomach wyżej, czyli `INFO`, `WARN`, `ERROR`. Dla porównania logger z konfiguracją `WARN` będzie przekazywał wpisy na poziomach `WARN` oraz `ERROR`. Im niższy poziom, tym więcej wpisów jest logowanych, a to z kolei implikuje spowolnienie działania aplikacji. Zawsze powiniśmy kierować się rozsądkiem i konkretne informacje logować na odpowiednich poziomach. `INFO` nie będzie odpowiednim poziomem na wrzucanie całych obiektów parametrów do logów. Tak samo `TRACE` nie będzie odpowiednim poziomem dla zalogowania niespodziewanego wyjątku.

Przy poziomie logowania powinniśmy kierować się następującymi wytycznymi:

![image](https://user-images.githubusercontent.com/5354498/80310706-65481880-87dc-11ea-9e60-a710883ed0c4.png)

### MDC - Mapping Diagnostic Context

To zestaw informacji, które są dołączane do każdego wpisu ([dokumentacja](http://logback.qos.ch/manual/mdc.html)), np. unikalny identyfikator żądania HTTP (wartość `48de937a1c45ef8a`):
```
2020-04-16 19:04:13.779 ERROR [48de937a1c45ef8a] 29726 --- [o-auto-1-exec-1] o.s.c.s.i.web.ExceptionLoggingFilter     : Uncaught exception thrown
```

### Konfiguracja

Skorzystamy z biblioteki `logback`. Podstawowa konfiguracja wygląda tak:
```xml
<configuration>
  <appender name="MY-STDOUT-APPENDER" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>

  <logger name="chapters.configuration" level="INFO" />
  <logger name="chapters.configuration.Foo" level="DEBUG" />

  <root level="DEBUG">
    <appender-ref ref="MY-STDOUT-APPENDER" />
  </root>
</configuration>
```

Gdzie:

* Konfiguracja `appender`'a o nazwie `MY-STDOUT-APPENDER`, który przekierowuje logi na `stdout` (`ConsoleAppender`, ale istnieją inne [appender'y](http://logback.qos.ch/manual/appenders.html#OutputStreamAppender)). Wewnątrz jest ustalony wzór wiadomości:
	```xml
	<appender name="MY-STDOUT-APPENDER" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
		  <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
		</encoder>
	</appender>
	```
* Konfiguracja `logger`'ów:
	* Chcemy logować wpisy od poziomu (włącznie) `INFO` dla wszystkich klas w pakiecie `chapters.configuration`:
		```xml
		<logger name="chapters.configuration" level="INFO" />
		```
	* Chcemy logować wpisy na poziomie `DEBUG` zalogowane z klasy `Foo` w pakiecie `chapters.configuration`:
		```xml
		<logger name="chapters.configuration.Foo" level="DEBUG" />
		```
	* Konfiguracja dla loggera bazowego. Określamy, że logger ma przekazywać logi na poziomie `DEBUG` (i wyżej) do `appender`'a o nazwie `MY-STDOOUT-APPENDER`. Konfiguracja bazowa jest używana domyślnie, jeżeli nie została nadpisana (tak jak np. wyżej, dla pakietu `chapters.configuration` oraz klasy `Foo` z tego pakietu):
		```xml
		<root level="DEBUG">
			<appender-ref ref="MY-STDOUT-APPENDER" />
		</root>
		```

### `stdout`/`stderr`

Substytutem logów są `System.out.println`. Chwilowo można z nich skorzystać, jednak długofalowo nie nadają się do logowania z kilku powodów:
* `System.out.println` to nic innego jak wypisanie czegoś na `stdout` (ewentualnie `System.err`). To oznacza, że aplikacja musiałaby być uruchomiona w taki sposób, aby cały output z `stdout`/`stderr` był przekierowany do jakiegoś pliku:
    ```
    $ ./aplikacja > all-logs.log
    ```
* Brak możliwości zaawansowanej konfiguracji i zarządzania loggerami

## TODO

- [ ] Dodać odpowiednie zależności - `logback-classic` - dodaje bibliotekę `logback-core` oraz API do logowania o nazwie `SLF4J` (`slf4j-api`)
	```groovy
	compile group: 'ch.qos.logback', name: 'logback-classic', version: '1.3.0-alpha5'
	```
- [ ] Dodać podstawową konfigurację `logback`, gdzie domyślny logger przyjmue logi na poziomie `INFO` oraz jeden `appender`, który wypisuje na `stdout`. Plik w `resources/logback.xml`:
	```xml
	<configuration>
	    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
	        <encoder>
	            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
	        </encoder>
	    </appender>

	    <root level="INFO">
	        <appender-ref ref="STDOUT"/>
	    </root>
	</configuration>
	```
- [ ] Aby skorzystać z logger'a w klasie, trzeba go dodać jako statyczne finalne pole:
	```java
	private static final Logger LOGGER = LoggerFactory.getLogger(GUIUsers.class); // Nazwa klasy, wewnątrz której używamy loggger'a
	```
	```java
	Completable.fromRunnable(() -> adminController.getUserManagement().enableUser(id))
	    .doOnComplete(() -> LOGGER.info("Enabling user process completed")) // <--------------- tutaj
	    .subscribeOn(enableUserScheduler)
	    .andThen(Single.fromCallable(this::getAllUsers))
	    .doOnSuccess(list -> LOGGER.info("All users ({}) has been fetched", list.size())) // <------ tutaj
	    .observeOn(JavaFxScheduler.platform())
	    .subscribe(usersList -> {
	        observableUsers.clear();
	        observableUsers.addAll(usersList);
	        fetchingLocked = false;
	    });
	```
- [ ] Przejrzeć kod w poszukiwaniu TODO z miejscami do potencjalnego zalogowania
