### ISSUE TITLE
Konfiguracja pipeline'ów

### ISSUE THREAD

**Issue by kr5ture** [qverkk/university-scheduler#22]
## TODO

Potrzebujemy kilku pipeline'ów:

- [ ] Budujący aplikację (`clean build verify`) - po każdym push'u. Dodatkowo powodzenie planu jest wymagane, aby dało się zrobić merge PR'a (oprócz approve'ów)
- [ ] Tworzący release, czyli:
    - [ ] Uruchamiany po stworzeniu tag'a
    - [ ] Zbudowanie plików wykonywalnych na docelowe platformy (`clean jpackage`)
    - [ ] Publikacja w/w plików jako release w GitHub
