### ISSUE TITLE
Podbicie JDK (8 -> 14)

### ISSUE THREAD

**Issue by kr5ture** [qverkk/university-scheduler#23]
## TODO

- [ ] Wstępna analiza współdziałania `JavaFX14` z `JPhoenix`
- [ ] Podbicie Gradle wrapper do najnowszej wersji (a przynajmniej >= 6.4.1)
- [ ] Dodanie odpowiedniej konfiguracji (`java { sourceCompability/targetCompability }`)
- [ ] Dodanie do zależności wymaganych bibliotek `JavaFX` w wersji 14
- [ ] Weryfikacja współdziałania `JavaFX14` z `JPhoenix`
